### ISSUE TITLE
Error with "groups" metrics

### ISSUE THREAD

**Issue by ergonlogic** [ginkgostreet/org.ndi.metrics#3]
While the metrics-client job log reports success, running this job manually results in the following notice:

> Notice: Undefined variable: limit in CRM_Contact_BAO_Group::getGroupList() (line 850 of .../civicrm/CRM/Contact/BAO/Group.php).

Commenting out [this block](https://github.com/ginkgostreet/org.ndi.metrics/blob/master/metrics.php#L163) resolves it.

**Comment by caracolmzd** [comment]
@ergonlogic This looks like an issue in core and is probably inconsequential. I'm guessing that the line in question is different in the master branch: I see that $limit is set conditionally and eventually used to build a SQL string in a way where being empty would not break the SQL.
https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Group.php#L880
Being empty would not cause a problem.
It is generally advised not to display errors and warning on production sites.
